# Generated by Django 4.0.6 on 2022-07-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=300, verbose_name='نام کاربری')),
                ('passworld', models.CharField(db_index=True, max_length=300, verbose_name='پسورد')),
                ('email', models.CharField(db_index=True, max_length=300, verbose_name='ایمیل')),
                ('ramz', models.CharField(db_index=True, max_length=300, verbose_name='رمز بازی (اضافه))')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product')),
            ],
        ),
    ]
