# Generated by Django 4.0.3 on 2022-06-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default=None, max_length=300, verbose_name='عنوان در url'),
            preserve_default=False,
        ),
    ]
