# Generated by Django 4.0.3 on 2022-06-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_productbrand_url_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='url_title',
        ),
    ]
