# Generated by Django 4.0.3 on 2022-03-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettung',
            new_name='SiteSetting',
        ),
    ]
