# Generated by Django 4.0.3 on 2022-03-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات اسلایدر')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=500, verbose_name='عنوان لینک')),
                ('image', models.ImageField(upload_to='images/site-setting/slider-images/', verbose_name='تصویر اسلایدر')),
                ('slider', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'تنظیمات اسلایدر',
                'verbose_name_plural': 'تنظیمات اسلایدر ها',
            },
        ),
    ]
