# Generated by Django 4.0.3 on 2022-03-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider',
        ),
    ]
