# Generated by Django 4.0.3 on 2022-04-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_options_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
