# Generated by Django 4.0.3 on 2022-06-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addres',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
    ]
